### ISSUE TITLE
Utiliser le fd du pipe du CGI pour lire sa reponse sans bloquer et le kill si il prend trop de temps

### ISSUE THREAD

**Issue by BPhilagor** [BPhilagor/WebServ#17]
Enlever les signaux de CGI et lui faire retourner son fd. Le rajouter a la kqueue et avec EV_SET ajouter un timer dessus : 
https://habr.com/en/articles/600123/#system-timer-events-with-kqueue.

**Comment by sophiakoulen** [comment]
J'ai remarqué aussi que si le cgi n'est pas trouvé, on renvoie une réponse incomplète et le client boucle à l'infini.

**Comment by znichola** [comment]
ah nice, we should add this as a bug

**Comment by znichola** [comment]
done.
