### ISSUE TITLE
Should we pass $SERVER['argc'] and $SERVER['argv']?

### ISSUE THREAD

**Issue by sophiakoulen** [BPhilagor/WebServ#42]
<img width="1058" alt="Screen Shot 2023-07-25 at 2 22 35 PM" src="https://github.com/BPhilagor/WebServ/assets/100098656/5aca05ef-829d-44f1-b83a-ea53ee59b258">

These variables are mentioned in the PHP documentation.
It seems logical to me that PHP generates them automatically, but that doesn't seem to be the case.

They are not in the CGI spec, so we're not obligated to define them.

But if we do set them, what should the syntax for ARGV be?

**Comment by znichola** [comment]
no, apparely apachie does no do it.
