### ISSUE TITLE
Should we change directory before launching the CGI ?

### ISSUE THREAD

**Issue by sophiakoulen** [BPhilagor/WebServ#43]
The subject seems to suggest that we need to change the working directory to be that of the script before launching the CGI.
However, everything seems to work fine without doing so.
PHP's `getcwd()` and `scandir` functions give the expected results.
<img width="762" alt="Screen Shot 2023-07-25 at 3 02 54 PM" src="https://github.com/BPhilagor/WebServ/assets/100098656/857e9ff3-79d2-485f-bbf8-06bd33a7ee54">
<img width="1268" alt="Screen Shot 2023-07-25 at 3 03 51 PM" src="https://github.com/BPhilagor/WebServ/assets/100098656/f16cdba8-47aa-461b-b90c-a787b38dc6be">

**Comment by znichola** [comment]
Yes, I think we must

**Comment by znichola** [comment]
yes and we do
