### ISSUE TITLE
do we respect the limit client body server config?

### ISSUE THREAD

**Issue by znichola** [BPhilagor/WebServ#59]
<img width="390" alt="Screen Shot 2023-08-03 at 10 30 25 AM" src="https://github.com/BPhilagor/WebServ/assets/12100623/78a1fef3-ad22-4033-b0df-9b13c6ea9aa7">

**Comment by BPhilagor** [comment]
Tested and approved !
<img width="684" alt="Capture d’écran 2023-08-03 à 12 48 02" src="https://github.com/BPhilagor/WebServ/assets/118199934/29f51b14-12ca-481c-ba28-c45fa383fc5f">
