### ISSUE TITLE
should use getaddrinfo

### ISSUE THREAD

**Issue by znichola** [BPhilagor/WebServ#9]
59.10.1 The getaddrinfo() Function
Given a host name and a service name, getaddrinfo() returns a list of socket address
structures, each of which contains an IP address and port number.
#include <sys/socket.h>
#include <netdb.h>
int getaddrinfo(const char *host, const char *service,
const struct addrinfo *hints, struct addrinfo **result);
Returns 0 on success, or nonzero on error

from the bible
https://static1.squarespace.com/static/59c4375b8a02c798d1cce06f/t/59cfb6a032601e11ca5b1cbe/1506784947301/The+Linux+Programming+Interface.pdf

courtecy of jerdos-s

**Comment by BPhilagor** [comment]
page 1213

**Comment by sophiakoulen** [comment]
<img width="1064" alt="Screen Shot 2023-07-25 at 11 54 55 AM" src="https://github.com/BPhilagor/WebServ/assets/100098656/4a9a676d-252e-4b1d-b793-f4fdad00d3ab">

From the PHP manual of the $_SERVER variables

**Comment by znichola** [comment]
maybe some time later, but for now we've got something figured out
